CREATE TABLE IF NOT EXISTS RECOMMENDATIONS
(
    ID           UUID PRIMARY KEY,
    PRODUCT_ID   UUID NOT NULL UNIQUE,
    PRODUCT_TEXT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS QUERIES
(
    ID                UUID PRIMARY KEY,
    RECOMMENDATION_ID UUID         NOT NULL,
    QUERY             VARCHAR(100) NOT NULL,
    ARGUMENTS         VARCHAR(255),
    NEGATE            BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS STATISTICS
(
    ID                UUID PRIMARY KEY,
    RECOMMENDATION_ID UUID NOT NULL,
    COUNT             INT DEFAULT 0
)